name: Pull Request
on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test -v -cover ./...
